import React, { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, Building2, CheckCircle2, ChevronRight, FileText, Globe2, RefreshCw, Search, ShieldCheck, Users, UserRoundCheck, XCircle } from 'lucide-react';
import { useData } from '../contexts/DataContext';
import { loadAdminOverview, type AdminOverviewSnapshot } from '../services/adminOverview';
import { UserRole } from '../types';

type AdminTab = 'overview' | 'users' | 'system';
type DirectoryUser = AdminOverviewSnapshot['directory'][number];
const roleLabel = (role: DirectoryUser['role']) => role === 'admin' ? 'Admin' : role === 'manager' ? 'Gestoría' : 'Trabajador';
const roleTone = (role: DirectoryUser['role']) => role === 'admin' ? 'bg-[var(--labora-soft-clay)] text-[var(--labora-clay)]' : role === 'manager' ? 'bg-[var(--labora-soft-amber)] text-[var(--labora-gold)]' : 'bg-[var(--labora-moss-soft)] text-[var(--labora-primary)]';
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Sin actividad';

const Metric = ({ label, value, detail, icon: Icon, urgent = false }: { label: string; value: number; detail: string; icon: React.ComponentType<{ size?: number }>; urgent?: boolean }) => (
  <article className="group rounded-[22px] border border-[var(--labora-border)] bg-[var(--labora-surface)] p-5 shadow-[0_10px_35px_rgba(30,42,36,0.045)] transition hover:-translate-y-0.5">
    <div className="flex items-start justify-between gap-4"><div><p className="labora-label text-[var(--labora-muted)]">{label}</p><p className="mt-3 text-[2rem] font-extrabold leading-none tracking-[-0.04em] text-[var(--labora-ink)]">{value.toLocaleString('es-ES')}</p><p className="mt-3 text-[11px] leading-relaxed text-[var(--labora-muted)]">{detail}</p></div><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-[14px] ${urgent ? 'bg-[var(--labora-soft-clay)] text-[var(--labora-clay)]' : 'bg-[var(--labora-moss-soft)] text-[var(--labora-primary)]'}`}><Icon size={18} /></span></div>
  </article>
);

const AdminDashboard: React.FC = () => {
  const { currentUser, users, incomes, expenses, documents, requirements, declarations } = useData();
  const [snapshot, setSnapshot] = useState<AdminOverviewSnapshot | null>(null);
  const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState<AdminTab>('overview'); const [query, setQuery] = useState('');
  const [roleFilter, setRoleFilter] = useState<'all' | DirectoryUser['role']>('all');
  const refresh = async () => { setLoading(true); setError(''); try { setSnapshot(await loadAdminOverview()); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo cargar el centro de control.'); } finally { setLoading(false); } };
  useEffect(() => { if (currentUser?.role === UserRole.ADMIN) void refresh(); }, [currentUser?.id, currentUser?.role]);
  const local = useMemo(() => ({ workers: users.filter(u => u.role === UserRole.RIDER).length, managers: users.filter(u => u.role === UserRole.MANAGER).length, admins: users.filter(u => u.role === UserRole.ADMIN).length, linked: users.filter(u => u.role === UserRole.RIDER && Boolean(u.managerId)).length, pendingRequirements: requirements.filter(i => i.status === 'pending').length, pendingDeclarations: declarations.filter(i => i.status !== 'filed').length }), [declarations, requirements, users]);
  const directory = snapshot?.directory || [];
  const filteredUsers = useMemo(() => { const needle = query.trim().toLowerCase(); return directory.filter(user => (roleFilter === 'all' || user.role === roleFilter) && (!needle || `${user.name} ${user.email} ${user.countryCode}`.toLowerCase().includes(needle))); }, [directory, query, roleFilter]);
  if (currentUser?.role !== UserRole.ADMIN) return <div className="rounded-[24px] border border-[var(--labora-border)] bg-[var(--labora-surface)] p-10 text-center"><ShieldCheck className="mx-auto text-[var(--labora-primary)]" size={34} /><h2 className="mt-4 text-xl font-extrabold">Área restringida</h2><p className="mt-2 text-sm text-[var(--labora-muted)]">Se necesita una cuenta administradora verificada.</p></div>;
  const counts = snapshot?.users || { total: users.length, workers: local.workers, managers: local.managers, admins: local.admins };
  const records = snapshot?.records || { documents: documents.length, incomes: incomes.length, expenses: expenses.length, pendingRequirements: local.pendingRequirements, pendingDeclarations: local.pendingDeclarations };
  const countries = (Object.entries(snapshot?.countries || {}) as Array<[string, number]>).sort((a, b) => b[1] - a[1]); const maxCountry = Math.max(1, ...countries.map(([, count]) => count));
  const linked = snapshot ? directory.filter(u => u.role === 'rider' && u.managerId).length : local.linked; const coverage = counts.workers ? Math.round(linked / counts.workers * 100) : 0;
  const tabs: Array<{ id: AdminTab; label: string; icon: React.ComponentType<{ size?: number }> }> = [{ id: 'overview', label: 'Vista general', icon: BarChart3 }, { id: 'users', label: 'Usuarios', icon: Users }, { id: 'system', label: 'Sistema', icon: Activity }];

  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-[30px] bg-[var(--labora-primary)] px-6 py-7 text-white shadow-[0_24px_70px_rgba(30,70,52,0.18)] sm:px-8"><div className="pointer-events-none absolute -right-20 -top-28 h-72 w-72 rounded-full border border-white/10 bg-white/[0.04]" /><div className="relative flex flex-col justify-between gap-7 xl:flex-row xl:items-end"><div><div className="flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[0.18em] text-white/60"><ShieldCheck size={14} /> Centro de control</div><h1 className="mt-4 text-3xl font-extrabold tracking-[-0.035em] sm:text-4xl">Labora+ está bajo control.</h1><div className="mt-4 flex flex-wrap items-center gap-3 text-xs text-white/65"><span className="inline-flex items-center gap-1.5"><span className={`h-2 w-2 rounded-full ${error ? 'bg-amber-300' : 'bg-emerald-300'}`} />{error ? 'Datos globales degradados' : 'Servicios operativos'}</span><span>·</span><span>{counts.total} cuentas</span><span>·</span><span>{records.documents} documentos</span></div></div><div className="flex items-center gap-3"><div className="rounded-2xl border border-white/15 bg-white/[0.07] px-4 py-3"><p className="text-[9px] font-bold uppercase tracking-[0.12em] text-white/50">Última lectura</p><p className="mt-1 text-xs font-bold">{snapshot ? formatDate(snapshot.generatedAt) : 'Solo sesión local'}</p></div><button type="button" onClick={() => void refresh()} disabled={loading} className="flex h-11 w-11 items-center justify-center rounded-2xl border border-white/15 bg-white/10 hover:bg-white/20 disabled:opacity-50" aria-label="Actualizar"><RefreshCw size={17} className={loading ? 'animate-spin' : ''} /></button></div></div></section>
    <div className="flex gap-1 overflow-x-auto rounded-2xl border border-[var(--labora-border)] bg-[var(--labora-surface)] p-1.5 shadow-sm">{tabs.map(item => { const Icon = item.icon; const active = tab === item.id; return <button key={item.id} type="button" onClick={() => setTab(item.id)} className={`flex min-w-max items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-bold ${active ? 'bg-[var(--labora-primary)] text-white' : 'text-[var(--labora-muted)] hover:bg-[var(--labora-surface-2)]'}`}><Icon size={15} />{item.label}</button>; })}</div>
    {error && <div role="status" className="flex gap-3 rounded-2xl border border-[var(--labora-border)] bg-[var(--labora-soft-clay)] px-4 py-3 text-xs text-[var(--labora-clay)]"><AlertTriangle size={16} />{error} Se muestran datos locales; no se inventan valores.</div>}
    {tab === 'overview' && <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Personas" value={counts.total} detail={`${counts.workers} trabajadores · ${counts.managers} gestorías`} icon={Users} /><Metric label="Evidencias" value={records.documents} detail="Documentos almacenados" icon={FileText} /><Metric label="Actividad" value={records.incomes + records.expenses} detail={`${records.incomes} ingresos · ${records.expenses} gastos`} icon={Activity} /><Metric label="Requiere atención" value={records.pendingRequirements + records.pendingDeclarations} detail={`${records.pendingRequirements} solicitudes · ${records.pendingDeclarations} declaraciones`} icon={AlertTriangle} urgent /></section><section className="grid gap-5 xl:grid-cols-[1.35fr_0.65fr]"><article className="rounded-[24px] border border-[var(--labora-border)] bg-[var(--labora-surface)] p-6 shadow-sm"><div className="flex justify-between"><div><p className="labora-label">Presencia de Labora+</p><h2 className="mt-2 text-xl font-extrabold">Usuarios por país</h2></div><Globe2 size={21} className="text-[var(--labora-primary)]" /></div><div className="mt-6 space-y-4">{countries.length ? countries.slice(0, 8).map(([country, count]) => <div key={country} className="grid grid-cols-[44px_1fr_36px] items-center gap-3 text-xs"><span className="font-extrabold">{country}</span><div className="h-2 overflow-hidden rounded-full bg-[var(--labora-surface-2)]"><div className="h-full rounded-full bg-[var(--labora-primary)]" style={{ width: `${Math.max(5, count / maxCountry * 100)}%` }} /></div><span className="text-right font-bold text-[var(--labora-muted)]">{count}</span></div>) : <p className="py-10 text-center text-sm text-[var(--labora-muted)]">Resumen global no disponible.</p>}</div></article><article className="rounded-[24px] border border-[var(--labora-border)] bg-[var(--labora-surface)] p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[var(--labora-moss-soft)] text-[var(--labora-primary)]"><Building2 size={18} /></span><div><p className="labora-label">Red profesional</p><h2 className="mt-1 font-extrabold">Cobertura de gestoría</h2></div></div><div className="mt-8 flex items-end justify-between"><p className="text-5xl font-extrabold tracking-[-0.06em]">{coverage}%</p><p className="text-right text-xs text-[var(--labora-muted)]">{linked} de {counts.workers}<br />trabajadores</p></div><div className="mt-5 h-2.5 overflow-hidden rounded-full bg-[var(--labora-surface-2)]"><div className="h-full rounded-full bg-[var(--labora-clay)]" style={{ width: `${coverage}%` }} /></div></article></section></>}
    {tab === 'users' && <section className="overflow-hidden rounded-[24px] border border-[var(--labora-border)] bg-[var(--labora-surface)] shadow-sm"><div className="border-b border-[var(--labora-border)] p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><p className="labora-label">Directorio protegido</p><h2 className="mt-2 text-xl font-extrabold">Usuarios de la plataforma</h2></div><div className="flex flex-col gap-2 sm:flex-row"><label className="relative"><Search size={15} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--labora-muted)]" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar usuario" className="w-full rounded-xl border border-[var(--labora-border)] bg-[var(--labora-canvas)] py-2.5 pl-10 pr-3 text-xs outline-none sm:w-64" /></label><select value={roleFilter} onChange={e => setRoleFilter(e.target.value as typeof roleFilter)} className="rounded-xl border border-[var(--labora-border)] bg-[var(--labora-canvas)] px-3 py-2.5 text-xs font-bold"><option value="all">Todos los roles</option><option value="rider">Trabajadores</option><option value="manager">Gestorías</option><option value="admin">Administradores</option></select></div></div></div><div className="divide-y divide-[var(--labora-border)]/70">{filteredUsers.map(user => <div key={user.id} className="grid gap-3 px-5 py-4 hover:bg-[var(--labora-surface-2)]/70 sm:grid-cols-[minmax(0,1.5fr)_110px_70px_minmax(150px,0.7fr)_20px] sm:items-center"><div className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-[var(--labora-moss-soft)] font-extrabold text-[var(--labora-primary)]">{user.name.slice(0, 1).toUpperCase()}</span><div className="min-w-0"><p className="truncate text-sm font-extrabold">{user.name}</p><p className="truncate text-[11px] text-[var(--labora-muted)]">{user.email}</p></div></div><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-extrabold ${roleTone(user.role)}`}>{roleLabel(user.role)}</span><span className="text-xs font-bold">{user.countryCode}</span><div><p className="text-[9px] font-bold uppercase text-[var(--labora-muted)]">Último acceso</p><p className="mt-1 text-[11px] font-semibold">{formatDate(user.lastSignInAt)}</p></div><ChevronRight size={15} className="hidden sm:block" /></div>)}{!filteredUsers.length && <div className="px-6 py-14 text-center text-sm text-[var(--labora-muted)]">No hay usuarios que coincidan.</div>}</div></section>}
    {tab === 'system' && <section className="grid gap-5 lg:grid-cols-2"><article className="rounded-[24px] border border-[var(--labora-border)] bg-[var(--labora-surface)] p-6 shadow-sm"><p className="labora-label">Estado actual</p><h2 className="mt-2 text-xl font-extrabold">Servicios esenciales</h2><div className="mt-5 space-y-2">{['Autenticación y sesiones', 'Roles y permisos', 'Documentos privados', 'Datos operativos', 'Solicitudes de gestoría', 'Resumen administrativo'].map(label => <div key={label} className="flex items-center justify-between rounded-xl bg-[var(--labora-surface-2)] px-4 py-3"><span className="text-xs font-bold">{label}</span><span className="flex items-center gap-1.5 text-[10px] font-extrabold text-[var(--labora-primary)]"><CheckCircle2 size={14} /> Operativo</span></div>)}</div></article><article className="rounded-[24px] border border-[var(--labora-border)] bg-[var(--labora-surface)] p-6 shadow-sm"><p className="labora-label">Autoridad del panel</p><h2 className="mt-2 text-xl font-extrabold">Mantenimiento seguro</h2><div className="mt-5 space-y-3"><div className="flex gap-3 rounded-xl bg-[var(--labora-moss-soft)] p-4"><UserRoundCheck size={18} className="text-[var(--labora-primary)]" /><div><p className="text-xs font-extrabold">Lectura global autorizada</p><p className="mt-1 text-[11px] text-[var(--labora-muted)]">JWT y rol admin validados en servidor.</p></div></div><div className="flex gap-3 rounded-xl bg-[var(--labora-soft-clay)] p-4"><XCircle size={18} className="text-[var(--labora-clay)]" /><div><p className="text-xs font-extrabold">Cambios críticos bloqueados</p><p className="mt-1 text-[11px] text-[var(--labora-muted)]">Borrar, suspender o cambiar roles requiere auditoría adicional.</p></div></div></div></article></section>}
  </div>;
};

export default AdminDashboard;
