import React, { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, Bell, CheckCircle2, ChevronRight, Clock3, FileText, Globe2, RefreshCw, Search, ShieldCheck, Users, UserRoundCheck, XCircle } from 'lucide-react';
import { useData } from '../contexts/DataContext';
import { loadAdminOverview, type AdminOverviewSnapshot } from '../services/adminOverview';
import { UserRole } from '../types';

type AdminTab = 'overview' | 'users' | 'system';
type DirectoryUser = AdminOverviewSnapshot['directory'][number];
const roleLabel = (role: DirectoryUser['role']) => role === 'admin' ? 'Admin' : role === 'manager' ? 'Gestoría' : 'Trabajador';
const roleTone = (role: DirectoryUser['role']) => role === 'admin' ? 'bg-[var(--labora-soft-clay)] text-[var(--labora-clay)]' : role === 'manager' ? 'bg-[color-mix(in_srgb,var(--labora-gold)_12%,var(--labora-surface))] text-[var(--labora-gold)]' : 'bg-[var(--labora-moss-soft)] text-[var(--labora-primary)]';
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Sin actividad';
const compactDate = (value: string) => new Intl.DateTimeFormat('es-ES', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value));

const AdminDashboard: React.FC = () => {
  const { currentUser, users, incomes, expenses, documents, requirements, declarations } = useData();
  const [snapshot, setSnapshot] = useState<AdminOverviewSnapshot | null>(null);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState<AdminTab>('overview');
  const [query, setQuery] = useState('');
  const [roleFilter, setRoleFilter] = useState<'all' | DirectoryUser['role']>('all');
  const refresh = async () => { setLoading(true); setError(''); try { setSnapshot(await loadAdminOverview()); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo cargar el centro de control.'); } finally { setLoading(false); } };
  useEffect(() => { if (currentUser?.role === UserRole.ADMIN) void refresh(); }, [currentUser?.id, currentUser?.role]);

  const local = useMemo(() => ({
    workers: users.filter(user => user.role === UserRole.RIDER).length,
    managers: users.filter(user => user.role === UserRole.MANAGER).length,
    admins: users.filter(user => user.role === UserRole.ADMIN).length,
    linked: users.filter(user => user.role === UserRole.RIDER && Boolean(user.managerId)).length,
    pendingRequirements: requirements.filter(item => item.status === 'pending').length,
    pendingDeclarations: declarations.filter(item => item.status !== 'filed').length
  }), [declarations, requirements, users]);
  const directory = snapshot?.directory || [];
  const counts = snapshot?.users || { total: users.length, workers: local.workers, managers: local.managers, admins: local.admins };
  const records = snapshot?.records || { documents: documents.length, incomes: incomes.length, expenses: expenses.length, pendingRequirements: local.pendingRequirements, pendingDeclarations: local.pendingDeclarations };
  const pendingTotal = records.pendingRequirements + records.pendingDeclarations;
  const countries = (Object.entries(snapshot?.countries || {}) as Array<[string, number]>).sort((a, b) => b[1] - a[1]);
  const linked = snapshot ? directory.filter(user => user.role === 'rider' && user.managerId).length : local.linked;
  const coverage = counts.workers ? Math.round((linked / counts.workers) * 100) : 0;
  const filteredUsers = useMemo(() => { const needle = query.trim().toLowerCase(); return directory.filter(user => (roleFilter === 'all' || user.role === roleFilter) && (!needle || `${user.name} ${user.email} ${user.countryCode}`.toLowerCase().includes(needle))); }, [directory, query, roleFilter]);
  const activity = useMemo(() => directory.flatMap(user => {
    const rows: Array<{ id: string; at: string; title: string; detail: string; kind: 'access' | 'created' }> = [];
    if (user.lastSignInAt) rows.push({ id: `${user.id}-access`, at: user.lastSignInAt, title: 'Acceso registrado', detail: `${user.name} · ${roleLabel(user.role)}`, kind: 'access' });
    if (user.createdAt) rows.push({ id: `${user.id}-created`, at: user.createdAt, title: 'Cuenta creada', detail: `${user.name} · ${user.countryCode || 'País sin indicar'}`, kind: 'created' });
    return rows;
  }).sort((a, b) => new Date(b.at).getTime() - new Date(a.at).getTime()).slice(0, 7), [directory]);

  if (currentUser?.role !== UserRole.ADMIN) return <div className="rounded-[24px] border border-[var(--labora-border)] bg-[var(--labora-surface)] p-10 text-center"><ShieldCheck className="mx-auto text-[var(--labora-primary)]" size={34} /><h2 className="mt-4 text-xl font-extrabold">Área restringida</h2><p className="mt-2 text-sm text-[var(--labora-muted)]">Se necesita una cuenta administradora verificada.</p></div>;
  const tabs: Array<{ id: AdminTab; label: string; icon: React.ComponentType<{ size?: number }> }> = [{ id: 'overview', label: 'Vista general', icon: BarChart3 }, { id: 'users', label: 'Usuarios', icon: Users }, { id: 'system', label: 'Sistema', icon: Activity }];

  return <div className="mx-auto max-w-[1440px] space-y-5 pb-10">
    <section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="labora-kicker text-[var(--labora-primary-2)]">Administración</p><h1 className="mt-1 text-[2.15rem] font-extrabold tracking-[-0.055em] text-[var(--labora-ink)] sm:text-[2.75rem]">Centro de control</h1><p className="mt-1 text-sm text-[var(--labora-muted)]">Personas, gestorías y evidencias con datos reales de la plataforma.</p></div><label className="relative block w-full xl:max-w-md"><Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-[var(--labora-muted)]" /><input value={query} onChange={event => setQuery(event.target.value)} onFocus={() => setTab('users')} placeholder="Buscar personas, gestorías o correo…" className="h-12 w-full rounded-[15px] border border-[var(--labora-border)] bg-[var(--labora-surface)] pl-11 pr-4 text-sm outline-none shadow-sm focus:border-[var(--labora-primary-2)]" /></label></section>

    <section className="grid overflow-hidden rounded-[18px] border border-[var(--labora-border)] bg-[var(--labora-moss-soft)] sm:grid-cols-2 xl:grid-cols-[1.15fr_.7fr_.7fr_.7fr_1.2fr_auto]">
      <StatusItem icon={ShieldCheck} label="Servicios" value={error ? 'Datos degradados' : 'Operativos'} state={!error} />
      <StatusItem icon={Users} label="Cuentas" value={String(counts.total)} detail={`${counts.workers} trabajadores`} />
      <StatusItem icon={FileText} label="Documentos" value={String(records.documents)} detail="almacenados" />
      <StatusItem icon={Bell} label="Peticiones" value={String(pendingTotal)} detail={pendingTotal ? 'por atender' : 'sin pendientes'} />
      <StatusItem icon={Clock3} label="Última lectura" value={snapshot ? compactDate(snapshot.generatedAt) : 'Sesión local'} detail={loading ? 'actualizando…' : 'datos comprobados'} />
      <button type="button" onClick={() => void refresh()} disabled={loading} className="m-3 flex min-h-11 items-center justify-center rounded-[13px] border border-[var(--labora-border)] bg-[var(--labora-surface)] px-4 text-[var(--labora-primary)] transition hover:-translate-y-0.5 disabled:opacity-50" aria-label="Actualizar datos"><RefreshCw size={17} className={loading ? 'animate-spin' : ''} /></button>
    </section>

    <div className="flex gap-1 overflow-x-auto border-b border-[var(--labora-border)] pb-2" role="tablist" aria-label="Secciones del centro de control">{tabs.map(item => { const Icon = item.icon; const active = tab === item.id; return <button key={item.id} type="button" role="tab" aria-selected={active} onClick={() => setTab(item.id)} className={`flex min-w-max items-center gap-2 rounded-[12px] px-4 py-2.5 text-xs font-extrabold transition ${active ? 'bg-[var(--labora-primary)] text-white shadow-sm' : 'text-[var(--labora-muted)] hover:bg-[var(--labora-surface-2)]'}`}><Icon size={15} />{item.label}</button>; })}</div>
    {error && <div role="status" className="flex gap-3 rounded-[16px] border border-[var(--labora-border)] bg-[var(--labora-soft-clay)] px-4 py-3 text-xs text-[var(--labora-clay-deep)]"><AlertTriangle size={16} />{error} Se muestran solo datos locales disponibles.</div>}

    {tab === 'overview' && <div className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,.85fr)]"><div className="space-y-5">
      <section className="border-b border-[var(--labora-border)] px-1 pb-6 pt-2"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="labora-kicker text-[var(--labora-muted)]">Resumen de hoy</p><h2 className="mt-3 font-serif text-[2.5rem] font-semibold leading-none tracking-[-0.045em] text-[var(--labora-ink)] sm:text-[3.35rem]">{pendingTotal ? 'Hay trabajo pendiente.' : 'Todo en orden.'}</h2><p className="mt-4 max-w-2xl text-sm leading-relaxed text-[var(--labora-muted)]">{counts.total} cuentas activas, {records.documents} documentos y {pendingTotal ? `${pendingTotal} elementos que requieren revisión.` : 'ninguna petición pendiente.'}</p></div><span className="mt-1 text-[11px] font-bold text-[var(--labora-muted)]">{new Intl.DateTimeFormat('es-ES', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date())}</span></div></section>
      <section className="overflow-hidden rounded-[20px] border border-[var(--labora-border)] bg-[var(--labora-surface)]"><header className="flex items-start justify-between gap-4 border-b border-[var(--labora-border)] px-5 py-4 sm:px-6"><div><p className="labora-kicker text-[var(--labora-muted)]">Actividad real</p><h2 className="mt-1 text-lg font-extrabold">Movimientos recientes</h2></div><button type="button" onClick={() => setTab('users')} className="flex items-center gap-1.5 text-xs font-extrabold text-[var(--labora-primary)]">Ver usuarios <ChevronRight size={14} /></button></header><div className="divide-y divide-[var(--labora-border)]/80">{activity.length ? activity.map((event, index) => <div key={event.id} className="grid grid-cols-[66px_38px_minmax(0,1fr)_auto] items-center gap-3 px-5 py-3.5 sm:px-6"><time className="text-[10px] font-bold text-[var(--labora-muted)]">{compactDate(event.at)}</time><span className={`flex h-9 w-9 items-center justify-center rounded-full ${index === 0 ? 'bg-[var(--labora-moss-soft)] text-[var(--labora-primary)]' : 'bg-[var(--labora-surface-2)] text-[var(--labora-muted)]'}`}>{event.kind === 'access' ? <UserRoundCheck size={16} /> : <Users size={16} />}</span><div className="min-w-0"><p className="truncate text-xs font-extrabold">{event.title}</p><p className="mt-0.5 truncate text-[11px] text-[var(--labora-muted)]">{event.detail}</p></div><span className="hidden rounded-full bg-[var(--labora-moss-soft)] px-2 py-1 text-[9px] font-bold text-[var(--labora-primary)] sm:block">Verificado</span></div>) : <div className="px-6 py-12 text-center"><Activity className="mx-auto text-[var(--labora-muted)]" size={24} /><p className="mt-3 text-sm font-extrabold">Aún no hay actividad disponible</p><p className="mt-1 text-xs text-[var(--labora-muted)]">Aparecerá aquí cuando el servidor registre accesos o nuevas cuentas.</p></div>}</div></section>
    </div><aside className="space-y-5">
      <section className={`rounded-[20px] border p-5 ${pendingTotal ? 'border-[var(--labora-border)] bg-[var(--labora-soft-clay)]' : 'border-[var(--labora-border)] bg-[var(--labora-surface)]'}`}><div className="flex items-start gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-full ${pendingTotal ? 'bg-[var(--labora-soft-clay)] text-[var(--labora-clay)]' : 'bg-[var(--labora-moss-soft)] text-[var(--labora-primary)]'}`}>{pendingTotal ? <Bell size={18} /> : <CheckCircle2 size={18} />}</span><div><p className="labora-kicker text-[var(--labora-clay)]">Requiere tu atención</p><h2 className="mt-2 text-lg font-extrabold">{pendingTotal ? `${pendingTotal} elementos pendientes` : 'No hay elementos pendientes'}</h2><p className="mt-2 text-xs leading-relaxed text-[var(--labora-muted)]">{pendingTotal ? `${records.pendingRequirements} peticiones y ${records.pendingDeclarations} declaraciones esperan revisión.` : 'Te avisaremos cuando una petición o declaración necesite revisión.'}</p></div></div></section>
      <section className="overflow-hidden rounded-[20px] border border-[var(--labora-border)] bg-[var(--labora-surface)]"><header className="flex items-center justify-between px-5 py-4"><div><p className="labora-kicker text-[var(--labora-muted)]">Solo administración</p><h2 className="mt-1 text-sm font-extrabold">Cobertura operativa</h2></div><Globe2 size={18} className="text-[var(--labora-primary)]" /></header><div className="border-y border-[var(--labora-border)] bg-[var(--labora-canvas)] px-3 py-2"><div className="aspect-[3/1] w-full overflow-hidden"><img src="./brand/admin-coverage-map.png" alt="Mapa mundial de cobertura de Labora+" className="h-full w-full object-contain" /></div></div><div className="flex min-h-11 flex-wrap gap-1.5 border-b border-[var(--labora-border)] px-4 py-3">{countries.length ? countries.slice(0, 4).map(([country, count]) => <span key={country} className="rounded-full bg-[var(--labora-moss-soft)] px-2.5 py-1 text-[9px] font-extrabold text-[var(--labora-primary)]">{country} · {count}</span>) : <span className="text-[10px] font-medium text-[var(--labora-muted)]">Sin países disponibles en esta lectura.</span>}</div><div className="grid grid-cols-2 divide-x divide-[var(--labora-border)]"><div className="p-4"><p className="text-[9px] font-bold uppercase tracking-[0.12em] text-[var(--labora-muted)]">Gestorías</p><p className="mt-1 text-xl font-extrabold">{counts.managers}</p></div><div className="p-4"><p className="text-[9px] font-bold uppercase tracking-[0.12em] text-[var(--labora-muted)]">Cobertura</p><p className="mt-1 text-xl font-extrabold">{coverage}%</p></div></div></section>
      <section className="rounded-[20px] border border-[var(--labora-border)] bg-[var(--labora-surface)] p-5"><div className="flex items-center justify-between"><div><p className="labora-kicker text-[var(--labora-muted)]">Estado del sistema</p><h2 className="mt-1 text-sm font-extrabold">Lectura disponible</h2></div><span className={`h-2.5 w-2.5 rounded-full ${error ? 'bg-amber-500' : 'bg-emerald-500'}`} /></div><div className="mt-4 divide-y divide-[var(--labora-border)]/80">{['Autenticación', 'Directorio protegido', 'Datos operativos'].map(label => <div key={label} className="flex items-center justify-between py-2.5 text-[11px]"><span className="font-bold">{label}</span><span className={error ? 'text-amber-700' : 'text-[var(--labora-primary)]'}>{error ? 'Comprobar' : 'Operativo'}</span></div>)}</div></section>
    </aside></div>}

    {tab === 'users' && <section className="overflow-hidden rounded-[22px] border border-[var(--labora-border)] bg-[var(--labora-surface)]"><header className="flex flex-col justify-between gap-4 border-b border-[var(--labora-border)] p-5 sm:flex-row sm:items-center sm:p-6"><div><p className="labora-kicker text-[var(--labora-muted)]">Directorio protegido</p><h2 className="mt-1 text-xl font-extrabold">Usuarios de la plataforma</h2></div><div className="flex flex-col gap-2 sm:flex-row"><label className="relative"><Search size={15} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--labora-muted)]" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar usuario" className="w-full rounded-xl border border-[var(--labora-border)] bg-[var(--labora-canvas)] py-2.5 pl-10 pr-3 text-xs outline-none sm:w-64" /></label><select value={roleFilter} onChange={event => setRoleFilter(event.target.value as typeof roleFilter)} className="rounded-xl border border-[var(--labora-border)] bg-[var(--labora-canvas)] px-3 py-2.5 text-xs font-bold"><option value="all">Todos los roles</option><option value="rider">Trabajadores</option><option value="manager">Gestorías</option><option value="admin">Administradores</option></select></div></header>{snapshot?.directoryTruncated && <p className="border-b border-[var(--labora-border)] bg-[var(--labora-soft-clay)] px-5 py-2 text-[10px] font-bold text-[var(--labora-clay-deep)]">La vista muestra los primeros 200 perfiles.</p>}<div className="divide-y divide-[var(--labora-border)]/70">{filteredUsers.map(user => <div key={user.id} className="grid gap-3 px-5 py-4 hover:bg-[var(--labora-surface-2)]/70 sm:grid-cols-[minmax(0,1.5fr)_110px_70px_minmax(150px,.7fr)_20px] sm:items-center"><div className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[var(--labora-moss-soft)] font-extrabold text-[var(--labora-primary)]">{user.name.slice(0, 1).toUpperCase()}</span><div className="min-w-0"><p className="truncate text-sm font-extrabold">{user.name}</p><p className="truncate text-[11px] text-[var(--labora-muted)]">{user.email}</p></div></div><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-extrabold ${roleTone(user.role)}`}>{roleLabel(user.role)}</span><span className="text-xs font-bold">{user.countryCode}</span><div><p className="text-[9px] font-bold uppercase text-[var(--labora-muted)]">Último acceso</p><p className="mt-1 text-[11px] font-semibold">{formatDate(user.lastSignInAt)}</p></div><ChevronRight size={15} className="hidden sm:block" /></div>)}{!filteredUsers.length && <div className="px-6 py-14 text-center text-sm text-[var(--labora-muted)]">No hay usuarios que coincidan.</div>}</div></section>}
    {tab === 'system' && <section className="grid gap-5 lg:grid-cols-2"><article className="rounded-[22px] border border-[var(--labora-border)] bg-[var(--labora-surface)] p-6"><p className="labora-kicker text-[var(--labora-muted)]">Estado observado</p><h2 className="mt-2 text-xl font-extrabold">Servicios esenciales</h2><div className="mt-5 divide-y divide-[var(--labora-border)]">{['Autenticación y sesiones', 'Roles y permisos', 'Documentos privados', 'Datos operativos', 'Solicitudes de gestoría', 'Resumen administrativo'].map(label => <div key={label} className="flex items-center justify-between py-3"><span className="text-xs font-bold">{label}</span><span className={`flex items-center gap-1.5 text-[10px] font-extrabold ${error ? 'text-amber-700' : 'text-[var(--labora-primary)]'}`}>{error ? <AlertTriangle size={14} /> : <CheckCircle2 size={14} />} {error ? 'Comprobar' : 'Operativo'}</span></div>)}</div></article><article className="rounded-[22px] border border-[var(--labora-border)] bg-[var(--labora-surface)] p-6"><p className="labora-kicker text-[var(--labora-muted)]">Autoridad del panel</p><h2 className="mt-2 text-xl font-extrabold">Mantenimiento seguro</h2><div className="mt-5 space-y-3"><div className="flex gap-3 rounded-xl bg-[var(--labora-moss-soft)] p-4"><UserRoundCheck size={18} className="text-[var(--labora-primary)]" /><div><p className="text-xs font-extrabold">Lectura global autorizada</p><p className="mt-1 text-[11px] text-[var(--labora-muted)]">JWT y rol admin validados en servidor.</p></div></div><div className="flex gap-3 rounded-xl bg-[var(--labora-soft-clay)] p-4"><XCircle size={18} className="text-[var(--labora-clay)]" /><div><p className="text-xs font-extrabold">Cambios críticos bloqueados</p><p className="mt-1 text-[11px] text-[var(--labora-muted)]">Borrar, suspender o cambiar roles requiere auditoría adicional.</p></div></div></div></article></section>}
  </div>;
};

const StatusItem = ({ icon: Icon, label, value, detail, state }: { icon: React.ComponentType<{ size?: number }>; label: string; value: string; detail?: string; state?: boolean }) => <div className="flex min-h-[76px] items-center gap-3 border-b border-[var(--labora-border)]/70 px-4 py-3 sm:border-r xl:border-b-0"><Icon size={19} className="shrink-0 text-[var(--labora-primary)]" /><div className="min-w-0"><p className="text-[9px] font-extrabold uppercase tracking-[0.11em] text-[var(--labora-muted)]">{label}</p><p className="mt-1 truncate text-sm font-extrabold">{typeof state === 'boolean' && <span className={`mr-2 inline-block h-2 w-2 rounded-full ${state ? 'bg-emerald-500' : 'bg-amber-500'}`} />}{value}</p>{detail && <p className="mt-0.5 truncate text-[9px] text-[var(--labora-muted)]">{detail}</p>}</div></div>;

export default AdminDashboard;
